### ISSUE TITLE
JSON from Angular to Play Controller gets $oid stripped on Angular 1.2.13

### ISSUE THREAD

**Issue by AndrewZurn** [lashford/modern-web-template#7]
Trying to write an update command and while sending the JSON back to the Play controller, Angular 1.2.13 strips out any $ characters, like the $oid which will cause validation errors.

Updating to the latest Angular version (1.3.6) fixed this issue.

If I get to it, I'll fork, update, test and submit a pull request.

**Comment by lashford** [comment]
Thanks for the Pr Andrew, its been merged and the latest greatest is in `master`.
